### ISSUE TITLE
Apache Solr 7.5+ Compatibility

### ISSUE THREAD

**Issue by Timopheym** [DiceTechJobs/SolrPlugins#1]
Hey @simonhughes22! Thanks a lot for an awesome set! I am very new to Solr, and I would like to ask what should I tune to make it work with 7.5+ version, may be I better start using older version, but it would be nice if I will be able to use the newest one. 
Thanks!

**Comment by simonhughes22** [comment]
@Timopheym sorry for the late reply. I am currently working on a 7.5 version, especially in Lieue of my talk in 2 weeks at the activate conference (new name for lucene revolution). The easiest way is to use Maven to upgrade the lucene and solr library versions to 7.5 and fix the compilation errors. However there's a lot of functionality in this repo, and I am guessing you are probably only interested in a small subset of it. So you may just want to clone the repo, take the sections of the code that you want in 7.5, and recompile just those parts against 7.5. In my opinion, the most useful parts are the token filters, the similarity functions and the MLT handlers (and related). A lot of the other components, such as the boolean parser, spell checker and suggester are somewhat custom to dice, and probably less useeful to a general audience. I would also advise against using a lot of bespoke code within solr where possible, but in certain circumstances, such as the MLT, the current solr implementation is lacking and so plugins are the way to go. At some point I just issue a PR to try and get some of this into solr core. Also note that some functionality in here is no longer needed or less useful, given the features added in solr 6 and 7. For example, you can currently use the payload_score query parser to leverage payloads as part of your scoring function (although that's still somewhat limited).
